owner_org: "acled"
author: "acled"
author_email: "info.africa@acleddata.com"
maintainer_email: "info.africa@acleddata.com"
license_id: "cc-by-sa"
subnational: 1  # has to be 0 or 1. Default 1 for ACLED.
notes: "ACLED conflict and protest data for African states from 1997 – December 2016 is available in Version 7 of the the ACLED dataset. Realtime data for 2017 is collected and published on a weekly basis, and will continue to be made available through the Climate Change and African Political Stability (CCAPS) website and on this page.


Due to the realtime nature of data collection which results in occasional reporting lags, and/or insufficient detail in early event reports for inclusion in the dataset, a small number of events in the 2017 data pre-date this period. These have been coded and published for the first time in 2017 and do not duplicate any events found in the full published dataset.


Data files are updated each Monday, containing data from the previous week. The data files below include a single running file for all 2017 data, with monthly files updated on an ongoing basis."
caveats: "Due to the realtime nature of data collection which results in occasional reporting lags, and/or insufficient detail in early event reports for inclusion in the dataset, a small number of events in the 2017 data pre-date this period. These have been coded and published for the first time in 2017 and do not duplicate any events found in the full published dataset."
methodology: "Other"
methodology_other: "This page contains information about how the ACLED team collects, cleans, reviews and checks event data, with a focus on what makes ACLED unique and compatible with other data. The process of ACLED coding assures that it is accurate, comprehensive, transparent and regularly updated. ACLED-Africa data is available from 1997 and into real time. ACLED-Asia produces publicly available real-time data and continues to backdate for all states. Data will be posted as it is complete.  For more information about its methodology, please consult [ACLED's Methodology page](http://www.acleddata.com/methodology/)."
dataset_source: "ACLED"
package_creator: "mcarans"
private: False  # has to be True or False
url: ~
state: "active"  # always "active".
