title: "Dynamic Map: Political Conflict in Africa"
notes: "The dynamic maps below have been drawn from ACLED Version 7. They illustrate key dynamics in event types, reported fatalities, and actor categories. Clicking on the maps, and selecting or de-selecting options in the legends, allows users to interactively edit and manipulate the visualisations, and export or share the finished visuals. The maps are visualised using Tableau Public."
url: "http://www.acleddata.com/visuals/maps/dynamic-maps/"
image_url: "http://docs.hdx.rwlabs.org/wp-content/uploads/acled_visual.png"
