# Collector specific configuration
acled_url: "https://api.acleddata.com/acled/read.csv?limit=0&"
countries_url: "https://www.acleddata.com/wp-content/uploads/dlm_uploads/2017/12/list-of-countries_Available.xlsx"
hxlproxy_url: "https://data.humdata.org/hxlproxy/data.csv?"
