# Collector specific configuration
acled_url: "https://api.acleddata.com/acled/read.csv?limit=0&terms=accept&"
countries_url: "https://www.acleddata.com/download/3987/"
hxlproxy_url: "https://data.humdata.org/hxlproxy/data.csv?"
