license_id: hdx-other
license_other: "By using ACLED data you agree to abide by the [Terms of Use and Attribution Policy](https://acleddata.com/terms-of-use/)."
methodology: Registry
caveats: ""
dataset_source: Armed Conflict Location & Event Data Project (ACLED)
package_creator: HDX Data Systems Team
private: False
maintainer: aa13de36-28c5-47a7-8d0b-6d7c754ba8c8
owner_org:  hdx-hapi
data_update_frequency: 7
notes: "This dataset contains data obtained from the\n[HDX Humanitarian API](https://hapi.humdata.org/) (HDX HAPI),\nwhich provides standardized humanitarian indicators designed\nfor seamless interoperability from multiple sources.\nThe data facilitates automated workflows and visualizations\nto support humanitarian decision making.\nFor more information, please see the HDX HAPI\n[landing page](https://data.humdata.org/hapi)\nand\n[documentation](https://hdx-hapi.readthedocs.io/en/latest/).\n"
subnational: "1"
dataset_preview: no_preview
