# Collector specific configuration

datasets:
  - "civilian-targeting-events-and-fatalities"
  - "demonstration-events"
  - "political-violence-events-and-fatalities"

resource_name: "Global Coordination & Context: Conflict Events (date_range)"

resource_description: "Conflict Event data from HDX HAPI (date_range), please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#conflict-events) for more information"

sheets:
  - "Non_HRP"
  - "HRP_1"
  - "HRP_2"

hxl_tags:
    "location_code": "#country+code"
    "has_hrp": "#meta+has_hrp"
    "in_gho": "#meta+in_gho"
    "provider_admin1_name": "#adm1+name+provider"
    "provider_admin2_name": "#adm2+name+provider"
    "admin1_code": "#adm1+code"
    "admin1_name": "#adm1+name"
    "admin2_code": "#adm2+code"
    "admin2_name": "#adm2+name"
    "admin_level": "#adm+level"
    "event_type": "#event+type"
    "events": "#indicator+event+num"
    "fatalities": "#affected+killed"
    "reference_period_start": "#date+start"
    "reference_period_end": "#date+end"
    "dataset_id": "#meta+dataset_id"
    "resource_id": "#meta+resource_id"
    "error": "#error"

tags:
  - "conflict-violence"
