# Collector specific configuration

datasets:
  - "civilian-targeting-events-and-fatalities"
  - "demonstration-events"
  - "political-violence-events-and-fatalities"

resource_name: "Global Coordination & Context: Conflict Events (year)"

resource_description: "Conflict Event data from HDX HAPI (year), please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#conflict-events) for more information"

sheets:
  - "Non_HRP"
  - "HRP_1"
  - "HRP_2"

headers:
  - location_code
  - has_hrp
  - in_gho
  - provider_admin1_name
  - provider_admin2_name
  - admin1_code
  - admin1_name
  - admin2_code
  - admin2_name
  - admin_level
  - event_type
  - events
  - fatalities
  - reference_period_start
  - reference_period_end
  - dataset_hdx_id
  - resource_hdx_id
  - warning
  - error

tags:
  - "conflict-violence"
  - "hxl"
